# Project information
site_name: Just A Bunch Of Starr Scripts
site_description: Just a bunch of scripts for Starr apps
site_author: Angry Cuban
site_url: https://psgsuite.io

# Repository
repo_name: angrycuban13/Just-A-Bunch-Of-Starr-Scripts
repo_url: https://github.com/angrycuban13/Just-A-Bunch-Of-Starr-Scripts/
