name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: docker://devblackops/github-action-psscriptanalyzer:2.4.0
        with:
          sendComment: true
          repoToken: ${{ secrets.PSSCRIPTANALYZER_PAT }}
          failOnErrors: true
          failOnWarnings: false
          failOnInfos: false
